name: Docker Image Prod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Prod Docker Image
      run: docker build . --file docker/Dockerfile --tag papermerge/auth:$(date +%s)
